import type {
  FlowDefinition,
  FlowNode,
  AiNode,
  AgentNode,
  BranchNode,
  ConditionNode,
  LoopNode,
  ParallelNode,
  HttpNode,
  MemoryNode,
  WaitNode,
  SleepNode,
  CodeNode,
  ExecNode,
  BaseNode,
} from "./types.js";

// ---- Cloudflare Workflows Transpiler --------------------------------------------
// Converts a clawflow definition into a Cloudflare WorkflowEntrypoint
// TypeScript class. This is the "write once, run anywhere" bridge.

export function transpileToCloudflare(flow: FlowDefinition): string {
  const className = toPascalCase(flow.flow);
  const nodeCode = flow.nodes.map((n) => transpileNode(n, 4)).join("\n\n");

  return `// Generated by clawflow transpiler
// Source flow: ${flow.flow}${flow.description ? `\n// ${flow.description}` : ""}
// To deploy: wrangler deploy

import { WorkflowEntrypoint, WorkflowStep, WorkflowEvent } from "cloudflare:workers";

type Env = {
  // Add your Cloudflare bindings here (KV, R2, AI, etc.)
  AI?: unknown;
  KV?: KVNamespace;
  [key: string]: unknown;
};

type Params = {
  [key: string]: unknown;
};

// Template filters
function applyFilter(val: unknown, filter: string): unknown {
  switch (filter) {
    case "json":
    case "tojson": return typeof val === "string" ? val : JSON.stringify(val);
    case "upper": return String(val).toUpperCase();
    case "lower": return String(val).toLowerCase();
    case "trim": return String(val).trim();
    case "length": {
      if (Array.isArray(val)) return val.length;
      if (typeof val === "string") return val.length;
      if (val !== null && typeof val === "object") return Object.keys(val).length;
      return 0;
    }
    default: return typeof val === "object" ? JSON.stringify(val) : String(val);
  }
}

// Resolve a dotted path against state
function getPath(obj: unknown, dotPath: string): unknown {
  return dotPath.split(".").reduce((o: unknown, k: string) =>
    o != null && typeof o === "object" ? (o as Record<string, unknown>)[k] : undefined, obj);
}

// Evaluate a simple condition for ternary templates
function evalTernaryCondition(state: Record<string, unknown>, expr: string): boolean {
  const m = expr.match(/^([\\w.]+)\\s*(==|!=|>=?|<=?)\\s*(.+)$/);
  if (!m) return !!getPath(state, expr);
  const left = getPath(state, m[1].trim());
  const rawRight = m[3].trim();
  const strMatch = rawRight.match(/^['"](.*)['"]$/);
  let right: unknown;
  if (strMatch) right = strMatch[1];
  else if (!isNaN(Number(rawRight))) right = Number(rawRight);
  else right = getPath(state, rawRight);
  switch (m[2]) {
    case "==": return left == right;
    case "!=": return left != right;
    case ">": return (left as number) > (right as number);
    case "<": return (left as number) < (right as number);
    case ">=": return (left as number) >= (right as number);
    case "<=": return (left as number) <= (right as number);
    default: return false;
  }
}

// Template resolver with ternary and wildcard support
function resolveTemplate(state: Record<string, unknown>, template: string): string {
  // Pass 1: ternary  {{ expr ? val1 : val2 }}
  let result = template.replace(
    /\\{\\{\\s*(.+?)\\s*\\?\\s*(.+?)\\s*:\\s*(.+?)\\s*\\}\\}/g,
    (_: string, cond: string, then_: string, else_: string) => {
      const chosen = evalTernaryCondition(state, cond.trim()) ? then_.trim() : else_.trim();
      const unquoted = chosen.replace(/^['"](.*)['"]$/, "$1");
      if (unquoted !== chosen) return unquoted;
      const val = getPath(state, chosen);
      return val !== undefined ? (typeof val === "object" ? JSON.stringify(val) : String(val)) : chosen;
    },
  );
  // Pass 2: wildcard  {{ path[*].field }}
  result = result.replace(
    /\\{\\{\\s*([\\w.]+)\\[\\*\\](?:\\.([\\w.]+))?\\s*\\}\\}/g,
    (_: string, arrPath: string, field?: string) => {
      const arr = getPath(state, arrPath);
      if (!Array.isArray(arr)) return \`{{\${arrPath}[*]\${field ? "." + field : ""}}}\`;
      const mapped = field ? arr.map((item: unknown) => getPath(item, field)) : arr;
      return JSON.stringify(mapped);
    },
  );
  // Pass 3: simple  {{ path | filter }}
  result = result.replace(/\\{\\{\\s*([\\w.]+)\\s*(?:\\|\\s*(\\w+))?\\s*\\}\\}/g, (_: string, path: string, filter?: string) => {
    const val = getPath(state, path);
    if (val === undefined) return \`{{\${path}}}\`;
    if (filter) return String(applyFilter(val, filter));
    return typeof val === "object" ? JSON.stringify(val) : String(val);
  });
  return result;
}

export class ${className} extends WorkflowEntrypoint<Env, Params> {
  async run(event: WorkflowEvent<Params>, step: WorkflowStep) {
    const state: Record<string, unknown> = { inputs: event.payload };

${nodeCode}

    return state;
  }
}
`;
}

// ---- Per-node transpilation -----------------------------------------------------

function transpileNode(node: FlowNode, indent: number): string {
  const pad = " ".repeat(indent);
  const retryConfig = node.retry
    ? `, { retries: { limit: ${node.retry.limit}, delay: "${node.retry.delay}"${node.retry.backoff ? `, backoff: "${node.retry.backoff}"` : ""} }${node.timeout ? `, timeout: "${node.timeout}"` : ""} }`
    : node.timeout
      ? `, { timeout: "${node.timeout}" }`
      : "";

  switch (node.do) {
    case "ai":
    case "agent": {
      const n = node as AiNode | AgentNode;
      const prompt = "prompt" in n ? n.prompt : (n as AgentNode).task;
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)};`
        : "";
      return `${pad}const ${camel(node.name)} = await step.do("${node.name}"${retryConfig}, async () => {
${pad}  const prompt = resolveTemplate(state, ${JSON.stringify(prompt)});
${pad}  // Call your AI provider here (Workers AI, Anthropic, OpenAI, etc.)
${pad}  // const result = await env.AI.run("@cf/meta/llama-3.1-8b-instruct", { prompt });
${pad}  throw new Error("Configure your AI provider binding in this step");
${pad}});${outputLine}`;
    }

    case "branch": {
      const n = node as BranchNode;
      const onParts = n.on.split(".");
      const stateAccess =
        onParts.length === 1
          ? `state["${onParts[0]}"]`
          : `(state["${onParts[0]}"] as Record<string, unknown>)?.["${onParts.slice(1).join('"]?.["')}"]`;
      const paths = Object.entries(n.paths)
        .map(([val, nodes], i) => {
          const innerCode = nodes.map((inner) => transpileNode(inner, indent + 2)).join("\n");
          return `${pad}${i === 0 ? "if" : "} else if"} (String(${stateAccess}) === "${val}") {\n${innerCode}`;
        })
        .join("\n");
      const defaultBlock = n.default
        ? `\n${pad}} else {\n${n.default.map((inner) => transpileNode(inner, indent + 2)).join("\n")}`
        : "";
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = String(${stateAccess});`
        : "";
      return `${pad}// branch: ${node.name}
${paths}${defaultBlock}
${pad}}${outputLine}`;
    }

    case "condition": {
      const n = node as ConditionNode;
      const thenCode = n.then
        .map((inner) => transpileNode(inner, indent + 2))
        .join("\n");
      const elseCode = n.else
        ? n.else.map((inner) => transpileNode(inner, indent + 2)).join("\n")
        : "";
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)};`
        : "";
      const elseBlock = elseCode
        ? `\n${pad}} else {\n${elseCode}`
        : "";
      return `${pad}// condition: ${node.name}
${pad}const ${camel(node.name)} = (() => {
${pad}  if (${n.if.replace(/([a-zA-Z_]\w*(?:\.\w+)+)/g, (_m: string, p: string) => {
        const parts = p.split(".");
        return parts.length === 1
          ? `state["${parts[0]}"]`
          : `(state["${parts[0]}"] as Record<string, unknown>)?.["${parts.slice(1).join('"]?.["')}"]`;
      })}) {
${thenCode}${elseBlock}
${pad}  }
${pad}  return true;
${pad}})();${outputLine}`;
    }

    case "loop": {
      const n = node as LoopNode;
      const innerCode = n.nodes
        .map((inner) => transpileNode(inner, indent + 2))
        .join("\n");
      const overParts = n.over.split(".");
      const overAccess =
        overParts.length === 1
          ? `state["${overParts[0]}"]`
          : `(state["${overParts[0]}"] as Record<string, unknown>)?.["${overParts.slice(1).join('"]?.["')}"]`;
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)}Results;`
        : "";
      return `${pad}const ${camel(node.name)}Results: unknown[] = [];
${pad}for (const ${n.as} of (${overAccess} as unknown[]) ?? []) {
${innerCode}
${pad}  ${camel(node.name)}Results.push(${n.as});
${pad}}${outputLine}`;
    }

    case "parallel": {
      const n = node as ParallelNode;
      const branches = n.nodes
        .map(
          (inner) =>
            `${pad}  step.do("${inner.name}"${retryConfig}, async () => {\n${pad}    // ${inner.do} node: ${inner.name}\n${pad}    throw new Error("Implement ${inner.name}");\n${pad}  })`,
        )
        .join(",\n");
      const fn = n.mode === "race" ? "Promise.race" : "Promise.all";
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)};`
        : "";
      return `${pad}const ${camel(node.name)} = await ${fn}([\n${branches}\n${pad}]);${outputLine}`;
    }

    case "http": {
      const n = node as HttpNode;
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)};`
        : "";
      return `${pad}const ${camel(node.name)} = await step.do("${node.name}"${retryConfig}, async () => {
${pad}  const url = resolveTemplate(state, ${JSON.stringify(n.url)});
${pad}  const resp = await fetch(url, {
${pad}    method: ${JSON.stringify(n.method ?? "GET")},
${pad}    headers: { "Content-Type": "application/json"${n.headers ? `, ...${JSON.stringify(n.headers)}` : ""} },
${pad}    ${n.body ? `body: resolveTemplate(state, ${JSON.stringify(typeof n.body === "string" ? n.body : JSON.stringify(n.body))})` : ""}
${pad}  });
${pad}  return resp.json();
${pad}});${outputLine}`;
    }

    case "memory": {
      const n = node as MemoryNode;
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)};`
        : "";
      const action =
        n.action === "write"
          ? `await env.KV.put(key, JSON.stringify(${n.value ? `resolveTemplate(state, ${JSON.stringify(n.value)})` : "null"}));`
          : n.action === "delete"
            ? `await env.KV.delete(key);`
            : `return JSON.parse(await env.KV.get(key) ?? "null");`;
      return `${pad}const ${camel(node.name)} = await step.do("${node.name}", async () => {
${pad}  const key = resolveTemplate(state, ${JSON.stringify(n.key)});
${pad}  ${action}
${pad}});${outputLine}`;
    }

    case "wait": {
      const n = node as WaitNode;
      const eventType =
        n.for === "approval" ? "approval" : (n.event ?? "event");
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)};`
        : "";
      return `${pad}const ${camel(node.name)} = await step.waitForEvent("${node.name}", {
${pad}  type: ${JSON.stringify(eventType)},
${pad}  timeout: "${n.timeout ?? "24 hours"}",
${pad}});${outputLine}`;
    }

    case "sleep": {
      const n = node as SleepNode;
      return `${pad}await step.sleep("${node.name}", "${n.duration}");`;
    }

    case "code": {
      const n = node as CodeNode;
      const inputParts = n.input?.split(".") ?? [];
      const inputExpr = n.input
        ? inputParts.length === 1
          ? `state["${inputParts[0]}"]`
          : `(state["${inputParts[0]}"] as Record<string, unknown>)?.["${inputParts.slice(1).join('"]?.["')}"]`
        : "undefined";
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)};`
        : "";
      return `${pad}const ${camel(node.name)} = (() => {
${pad}  const input = ${inputExpr};
${pad}  return (${n.run});
${pad}})();${outputLine}`;
    }

    case "exec": {
      const n = node as ExecNode;
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)};`
        : "";
      const cwdLine = n.cwd
        ? `\n${pad}  const cwd = resolveTemplate(state, ${JSON.stringify(n.cwd)});`
        : "";
      return `${pad}const ${camel(node.name)} = await step.do("${node.name}"${retryConfig}, async () => {
${pad}  const { exec } = await import("child_process");
${pad}  const { promisify } = await import("util");
${pad}  const execAsync = promisify(exec);
${pad}  const command = resolveTemplate(state, ${JSON.stringify(n.command)});${cwdLine}
${pad}  try {
${pad}    const { stdout, stderr } = await execAsync(command${n.cwd ? ", { cwd }" : ""});
${pad}    return { stdout: stdout.trimEnd(), stderr: stderr.trimEnd(), exitCode: 0 };
${pad}  } catch (e: any) {
${pad}    if (e.code != null && e.stdout !== undefined) {
${pad}      return { stdout: (e.stdout ?? "").trimEnd(), stderr: (e.stderr ?? "").trimEnd(), exitCode: e.code };
${pad}    }
${pad}    throw e;
${pad}  }
${pad}});${outputLine}`;
    }

    default:
      return `${pad}// Unknown node type: ${(node as BaseNode).do}`;
  }
}

// ---- Helpers --------------------------------------------------------------------

function toPascalCase(s: string): string {
  return (
    s
      .replace(/[-_](.)/g, (_, c: string) => c.toUpperCase())
      .replace(/^(.)/, (_, c: string) => c.toUpperCase()) + "Workflow"
  );
}

function camel(s: string): string {
  return s.replace(/[-_](.)/g, (_, c: string) => c.toUpperCase());
}
