import type {
  FlowDefinition,
  FlowNode,
  AiNode,
  AgentNode,
  BranchNode,
  ConditionNode,
  LoopNode,
  ParallelNode,
  HttpNode,
  MemoryNode,
  WaitNode,
  SleepNode,
  CodeNode,
  BaseNode,
} from "./types.js";

// ---- Cloudflare Workflows Transpiler --------------------------------------------
// Converts a clawflow definition into a Cloudflare WorkflowEntrypoint
// TypeScript class. This is the "write once, run anywhere" bridge.

export function transpileToCloudflare(flow: FlowDefinition): string {
  const className = toPascalCase(flow.flow);
  const nodeCode = flow.nodes.map((n) => transpileNode(n, 4)).join("\n\n");

  return `// Generated by clawflow transpiler
// Source flow: ${flow.flow}${flow.description ? `\n// ${flow.description}` : ""}
// To deploy: wrangler deploy

import { WorkflowEntrypoint, WorkflowStep, WorkflowEvent } from "cloudflare:workers";

type Env = {
  // Add your Cloudflare bindings here (KV, R2, AI, etc.)
  AI?: unknown;
  KV?: KVNamespace;
  [key: string]: unknown;
};

type Params = {
  [key: string]: unknown;
};

// Template resolver
function resolveTemplate(state: Record<string, unknown>, template: string): string {
  return template.replace(/\\{\\{\\s*([\\w.]+)\\s*\\}\\}/g, (_, path: string) => {
    const val = path.split(".").reduce((o: unknown, k: string) =>
      o != null && typeof o === "object" ? (o as Record<string, unknown>)[k] : undefined, state);
    return val === undefined ? \`{{\${path}}}\` : typeof val === "object" ? JSON.stringify(val) : String(val);
  });
}

export class ${className} extends WorkflowEntrypoint<Env, Params> {
  async run(event: WorkflowEvent<Params>, step: WorkflowStep) {
    const state: Record<string, unknown> = { trigger: event.payload };

${nodeCode}

    return state;
  }
}
`;
}

// ---- Per-node transpilation -----------------------------------------------------

function transpileNode(node: FlowNode, indent: number): string {
  const pad = " ".repeat(indent);
  const retryConfig = node.retry
    ? `, { retries: { limit: ${node.retry.limit}, delay: "${node.retry.delay}"${node.retry.backoff ? `, backoff: "${node.retry.backoff}"` : ""} }${node.timeout ? `, timeout: "${node.timeout}"` : ""} }`
    : node.timeout
      ? `, { timeout: "${node.timeout}" }`
      : "";

  switch (node.do) {
    case "ai":
    case "agent": {
      const n = node as AiNode | AgentNode;
      const prompt = "prompt" in n ? n.prompt : (n as AgentNode).task;
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)};`
        : "";
      return `${pad}const ${camel(node.name)} = await step.do("${node.name}"${retryConfig}, async () => {
${pad}  const prompt = resolveTemplate(state, ${JSON.stringify(prompt)});
${pad}  // Call your AI provider here (Workers AI, Anthropic, OpenAI, etc.)
${pad}  // const result = await env.AI.run("@cf/meta/llama-3.1-8b-instruct", { prompt });
${pad}  throw new Error("Configure your AI provider binding in this step");
${pad}});${outputLine}`;
    }

    case "branch": {
      const n = node as BranchNode;
      const onParts = n.on.split(".");
      const stateAccess =
        onParts.length === 1
          ? `state["${onParts[0]}"]`
          : `(state["${onParts[0]}"] as Record<string, unknown>)?.["${onParts.slice(1).join('"]?.["')}"]`;
      const paths = Object.entries(n.paths)
        .map(
          ([val, target], i) =>
            `${pad}${i === 0 ? "if" : "} else if"} (String(${stateAccess}) === "${val}") {\n${pad}  // -> ${target}`,
        )
        .join("\n");
      const defaultLine = n.default
        ? `\n${pad}} else {\n${pad}  // -> ${n.default}`
        : "";
      return `${pad}// branch: ${node.name}
${paths}${defaultLine}
${pad}}
${pad}// Note: Cloudflare Workflows don't support goto. Restructure branched
${pad}// nodes into separate methods or if/else blocks for production use.`;
    }

    case "condition": {
      const n = node as ConditionNode;
      const thenCode = n.then
        .map((inner) => transpileNode(inner, indent + 2))
        .join("\n");
      const elseCode = n.else
        ? n.else.map((inner) => transpileNode(inner, indent + 2)).join("\n")
        : "";
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)};`
        : "";
      const elseBlock = elseCode
        ? `\n${pad}} else {\n${elseCode}`
        : "";
      return `${pad}// condition: ${node.name}
${pad}const ${camel(node.name)} = (() => {
${pad}  if (${n.if.replace(/([a-zA-Z_]\w*(?:\.\w+)+)/g, (_m: string, p: string) => {
        const parts = p.split(".");
        return parts.length === 1
          ? `state["${parts[0]}"]`
          : `(state["${parts[0]}"] as Record<string, unknown>)?.["${parts.slice(1).join('"]?.["')}"]`;
      })}) {
${thenCode}${elseBlock}
${pad}  }
${pad}  return true;
${pad}})();${outputLine}`;
    }

    case "loop": {
      const n = node as LoopNode;
      const innerCode = n.nodes
        .map((inner) => transpileNode(inner, indent + 2))
        .join("\n");
      const overParts = n.over.split(".");
      const overAccess =
        overParts.length === 1
          ? `state["${overParts[0]}"]`
          : `(state["${overParts[0]}"] as Record<string, unknown>)?.["${overParts.slice(1).join('"]?.["')}"]`;
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)}Results;`
        : "";
      return `${pad}const ${camel(node.name)}Results: unknown[] = [];
${pad}for (const ${n.as} of (${overAccess} as unknown[]) ?? []) {
${innerCode}
${pad}  ${camel(node.name)}Results.push(${n.as});
${pad}}${outputLine}`;
    }

    case "parallel": {
      const n = node as ParallelNode;
      const branches = n.nodes
        .map(
          (inner) =>
            `${pad}  step.do("${inner.name}"${retryConfig}, async () => {\n${pad}    // ${inner.do} node: ${inner.name}\n${pad}    throw new Error("Implement ${inner.name}");\n${pad}  })`,
        )
        .join(",\n");
      const fn = n.mode === "race" ? "Promise.race" : "Promise.all";
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)};`
        : "";
      return `${pad}const ${camel(node.name)} = await ${fn}([\n${branches}\n${pad}]);${outputLine}`;
    }

    case "http": {
      const n = node as HttpNode;
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)};`
        : "";
      return `${pad}const ${camel(node.name)} = await step.do("${node.name}"${retryConfig}, async () => {
${pad}  const url = resolveTemplate(state, ${JSON.stringify(n.url)});
${pad}  const resp = await fetch(url, {
${pad}    method: ${JSON.stringify(n.method ?? "GET")},
${pad}    headers: { "Content-Type": "application/json"${n.headers ? `, ...${JSON.stringify(n.headers)}` : ""} },
${pad}    ${n.body ? `body: resolveTemplate(state, ${JSON.stringify(typeof n.body === "string" ? n.body : JSON.stringify(n.body))})` : ""}
${pad}  });
${pad}  return resp.json();
${pad}});${outputLine}`;
    }

    case "memory": {
      const n = node as MemoryNode;
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)};`
        : "";
      const action =
        n.action === "write"
          ? `await env.KV.put(key, JSON.stringify(${n.value ? `resolveTemplate(state, ${JSON.stringify(n.value)})` : "null"}));`
          : n.action === "delete"
            ? `await env.KV.delete(key);`
            : `return JSON.parse(await env.KV.get(key) ?? "null");`;
      return `${pad}const ${camel(node.name)} = await step.do("${node.name}", async () => {
${pad}  const key = resolveTemplate(state, ${JSON.stringify(n.key)});
${pad}  ${action}
${pad}});${outputLine}`;
    }

    case "wait": {
      const n = node as WaitNode;
      const eventType =
        n.for === "approval" ? "approval" : (n.event ?? "event");
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)};`
        : "";
      return `${pad}const ${camel(node.name)} = await step.waitForEvent("${node.name}", {
${pad}  type: ${JSON.stringify(eventType)},
${pad}  timeout: "${n.timeout ?? "24 hours"}",
${pad}});${outputLine}`;
    }

    case "sleep": {
      const n = node as SleepNode;
      return `${pad}await step.sleep("${node.name}", "${n.duration}");`;
    }

    case "code": {
      const n = node as CodeNode;
      const inputParts = n.input?.split(".") ?? [];
      const inputExpr = n.input
        ? inputParts.length === 1
          ? `state["${inputParts[0]}"]`
          : `(state["${inputParts[0]}"] as Record<string, unknown>)?.["${inputParts.slice(1).join('"]?.["')}"]`
        : "undefined";
      const outputLine = n.output
        ? `\n${pad}state["${n.output}"] = ${camel(node.name)};`
        : "";
      return `${pad}const ${camel(node.name)} = (() => {
${pad}  const input = ${inputExpr};
${pad}  return (${n.run});
${pad}})();${outputLine}`;
    }

    default:
      return `${pad}// Unknown node type: ${(node as BaseNode).do}`;
  }
}

// ---- Helpers --------------------------------------------------------------------

function toPascalCase(s: string): string {
  return (
    s
      .replace(/[-_](.)/g, (_, c: string) => c.toUpperCase())
      .replace(/^(.)/, (_, c: string) => c.toUpperCase()) + "Workflow"
  );
}

function camel(s: string): string {
  return s.replace(/[-_](.)/g, (_, c: string) => c.toUpperCase());
}
